// <auto-generated />
namespace BL.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewUserRoles_And_SystemLogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewUserRoles_And_SystemLogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201610212042316_NewUserRoles_And_SystemLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
