// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace BL.Database.Migrations
{
   
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Corrections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Corrections));
        
        string IMigrationMetadata.Id
        {
            get { return "201601271146111_Corrections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
