// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace BL.Database.Migrations
{
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delete_Incoming : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_Incoming));
        
        string IMigrationMetadata.Id
        {
            get { return "201602011414067_delete_Incoming"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
