namespace BL.Database.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RefactorSystemTables : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("DMS.DocumentAccesses", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.DictionaryPositionExecutors", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.DicStandartSendListContents", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.DocumentSendLists", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.DocumentRestrictedSendLists", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.TempDocRestrictedSendLists", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.TemplateDocumentSendLists", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.DictionaryPositionExecutors", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentSubscriptions", "CertificatePositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentEventAccesses", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentSendLists", "SourcePositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentSendLists", "TargetPositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentTasks", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentFiles", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentEvents", "SourcePositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentEvents", "TargetPositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.Documents", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentLinks", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DictionaryPositions", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.SystemActions", "GrantId", "DMS.SystemActions");
            DropForeignKey("DMS.SystemLogs", "ActionId", "DMS.SystemActions");
            DropForeignKey("DMS.SystemUIElements", "ActionId", "DMS.SystemActions");
            DropForeignKey("DMS.SystemActions", "ObjectId", "DMS.SystemObjects");
            DropForeignKey("DMS.SystemFields", "ObjectId", "DMS.SystemObjects");
            DropForeignKey("DMS.SystemLogs", "ObjectId", "DMS.SystemObjects");
            DropForeignKey("DMS.PropertyLinks", "ObjectId", "DMS.SystemObjects");
            DropForeignKey("DMS.SystemFields", "ValueTypeId", "DMS.SystemValueTypes");
            DropForeignKey("DMS.SystemSettings", "ValueTypeId", "DMS.SystemValueTypes");
            DropForeignKey("DMS.Properties", "ValueTypeId", "DMS.SystemValueTypes");
            DropForeignKey("DMS.SystemUIElements", "ValueTypeId", "DMS.SystemValueTypes");
            DropForeignKey("DMS.Documents", "DocumentDirectionId", "DMS.DictionaryDocumentDirections");
            DropForeignKey("DMS.TemplateDocuments", "DocumentDirectionId", "DMS.DictionaryDocumentDirections");
            DropForeignKey("DMS.DicStandartSendListContents", "SendTypeId", "DMS.DictionarySendTypes");
            DropForeignKey("DMS.DocumentSendLists", "SendTypeId", "DMS.DictionarySendTypes");
            DropForeignKey("DMS.TemplateDocumentSendLists", "SendTypeId", "DMS.DictionarySendTypes");
            DropForeignKey("DMS.DictionarySendTypes", "SubordinationTypeId", "DMS.DictionarySubordinationTypes");
            DropForeignKey("DMS.AdminSubordinations", "SubordinationTypeId", "DMS.DictionarySubordinationTypes");
            DropForeignKey("DMS.DocumentSendLists", "StageTypeId", "DMS.DictionaryStageTypes");
            DropForeignKey("DMS.TemplateDocumentSendLists", "StageTypeId", "DMS.DictionaryStageTypes");
            DropForeignKey("DMS.DocumentEvents", "EventTypeId", "DMS.DictionaryEventTypes");
            DropForeignKey("DMS.DictionaryEventTypes", "ImportanceEventTypeId", "DMS.DictionaryImportanceEventTypes");
            DropForeignKey("DMS.DocumentFiles", "TypeId", "DMS.DictionaryFileTypes");
            DropForeignKey("DMS.TemplateDocumentFiles", "TypeId", "DMS.DictionaryFileTypes");
            DropForeignKey("DMS.DocumentWaits", "ResultTypeId", "DMS.DictionaryResultTypes");
            DropForeignKey("DMS.DocumentLinks", "LinkTypeId", "DMS.DictionaryLinkTypes");
            DropForeignKey("DMS.AdminRegistrationJournalPositions", "RegJournalAccessTypeId", "DMS.DicRegJournalAccessTypes");
            DropForeignKey("DMS.DocumentSubscriptions", "SigningTypeId", "DMS.DictionarySigningTypes");
            DropForeignKey("DMS.DocumentSubscriptions", "SubscriptionStateId", "DMS.DictionarySubscriptionStates");
            DropForeignKey("DMS.SystemSettings", "SettingTypeId", "DMS.DictionarySettingTypes");
            RenameColumn(table: "DMS.SystemActions", name: "GrantId", newName: "SystemActions_Id");
            RenameIndex(table: "DMS.SystemActions", name: "IX_GrantId", newName: "IX_SystemActions_Id");
            DropPrimaryKey("DMS.AdminAccessLevels");
            DropPrimaryKey("DMS.DicPositionExecutorTypes");
            DropPrimaryKey("DMS.SystemActions");
            DropPrimaryKey("DMS.SystemObjects");
            DropPrimaryKey("DMS.SystemFields");
            DropPrimaryKey("DMS.SystemValueTypes");
            DropPrimaryKey("DMS.DictionaryDocumentDirections");
            DropPrimaryKey("DMS.DictionarySendTypes");
            DropPrimaryKey("DMS.DictionarySubordinationTypes");
            DropPrimaryKey("DMS.DictionaryStageTypes");
            DropPrimaryKey("DMS.DictionaryEventTypes");
            DropPrimaryKey("DMS.DictionaryImportanceEventTypes");
            DropPrimaryKey("DMS.DictionaryFileTypes");
            DropPrimaryKey("DMS.DictionaryResultTypes");
            DropPrimaryKey("DMS.DictionaryLinkTypes");
            DropPrimaryKey("DMS.DicRegJournalAccessTypes");
            DropPrimaryKey("DMS.DictionarySigningTypes");
            DropPrimaryKey("DMS.DictionarySubscriptionStates");
            DropPrimaryKey("DMS.DictionarySettingTypes");
            DropPrimaryKey("DMS.SystemFormats");
            DropPrimaryKey("DMS.SystemFormulas");
            DropPrimaryKey("DMS.SystemPatterns");
            DropPrimaryKey("DMS.SystemUIElements");
            AddColumn("DMS.DictionaryFileTypes", "Code", c => c.String(maxLength: 400));
            AddColumn("DMS.DictionarySigningTypes", "Code", c => c.String(maxLength: 400));
            AlterColumn("DMS.AdminAccessLevels", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DicPositionExecutorTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.SystemActions", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.SystemObjects", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.SystemFields", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.SystemValueTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionaryDocumentDirections", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionarySendTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionarySubordinationTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionaryStageTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionaryEventTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionaryImportanceEventTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionaryFileTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionaryResultTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionaryLinkTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DicRegJournalAccessTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionarySigningTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionarySubscriptionStates", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.DictionarySettingTypes", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.SystemFormats", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.SystemFormulas", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.SystemPatterns", "Id", c => c.Int(nullable: false));
            AlterColumn("DMS.SystemUIElements", "Id", c => c.Int(nullable: false));
            AddPrimaryKey("DMS.AdminAccessLevels", "Id");
            AddPrimaryKey("DMS.DicPositionExecutorTypes", "Id");
            AddPrimaryKey("DMS.SystemActions", "Id");
            AddPrimaryKey("DMS.SystemObjects", "Id");
            AddPrimaryKey("DMS.SystemFields", "Id");
            AddPrimaryKey("DMS.SystemValueTypes", "Id");
            AddPrimaryKey("DMS.DictionaryDocumentDirections", "Id");
            AddPrimaryKey("DMS.DictionarySendTypes", "Id");
            AddPrimaryKey("DMS.DictionarySubordinationTypes", "Id");
            AddPrimaryKey("DMS.DictionaryStageTypes", "Id");
            AddPrimaryKey("DMS.DictionaryEventTypes", "Id");
            AddPrimaryKey("DMS.DictionaryImportanceEventTypes", "Id");
            AddPrimaryKey("DMS.DictionaryFileTypes", "Id");
            AddPrimaryKey("DMS.DictionaryResultTypes", "Id");
            AddPrimaryKey("DMS.DictionaryLinkTypes", "Id");
            AddPrimaryKey("DMS.DicRegJournalAccessTypes", "Id");
            AddPrimaryKey("DMS.DictionarySigningTypes", "Id");
            AddPrimaryKey("DMS.DictionarySubscriptionStates", "Id");
            AddPrimaryKey("DMS.DictionarySettingTypes", "Id");
            AddPrimaryKey("DMS.SystemFormats", "Id");
            AddPrimaryKey("DMS.SystemFormulas", "Id");
            AddPrimaryKey("DMS.SystemPatterns", "Id");
            AddPrimaryKey("DMS.SystemUIElements", "Id");
            AddForeignKey("DMS.DocumentAccesses", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.DictionaryPositionExecutors", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.DicStandartSendListContents", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.DocumentSendLists", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.DocumentRestrictedSendLists", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.TempDocRestrictedSendLists", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.TemplateDocumentSendLists", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.DictionaryPositionExecutors", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentSubscriptions", "CertificatePositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentEventAccesses", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentSendLists", "SourcePositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentSendLists", "TargetPositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentTasks", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentFiles", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentEvents", "SourcePositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentEvents", "TargetPositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.Documents", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentLinks", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DictionaryPositions", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.SystemActions", "SystemActions_Id", "DMS.SystemActions", "Id");
            AddForeignKey("DMS.SystemLogs", "ActionId", "DMS.SystemActions", "Id");
            AddForeignKey("DMS.SystemUIElements", "ActionId", "DMS.SystemActions", "Id");
            AddForeignKey("DMS.SystemActions", "ObjectId", "DMS.SystemObjects", "Id");
            AddForeignKey("DMS.SystemFields", "ObjectId", "DMS.SystemObjects", "Id");
            AddForeignKey("DMS.SystemLogs", "ObjectId", "DMS.SystemObjects", "Id");
            AddForeignKey("DMS.PropertyLinks", "ObjectId", "DMS.SystemObjects", "Id");
            AddForeignKey("DMS.SystemFields", "ValueTypeId", "DMS.SystemValueTypes", "Id");
            AddForeignKey("DMS.SystemSettings", "ValueTypeId", "DMS.SystemValueTypes", "Id");
            AddForeignKey("DMS.Properties", "ValueTypeId", "DMS.SystemValueTypes", "Id");
            AddForeignKey("DMS.SystemUIElements", "ValueTypeId", "DMS.SystemValueTypes", "Id");
            AddForeignKey("DMS.Documents", "DocumentDirectionId", "DMS.DictionaryDocumentDirections", "Id");
            AddForeignKey("DMS.TemplateDocuments", "DocumentDirectionId", "DMS.DictionaryDocumentDirections", "Id");
            AddForeignKey("DMS.DicStandartSendListContents", "SendTypeId", "DMS.DictionarySendTypes", "Id");
            AddForeignKey("DMS.DocumentSendLists", "SendTypeId", "DMS.DictionarySendTypes", "Id");
            AddForeignKey("DMS.TemplateDocumentSendLists", "SendTypeId", "DMS.DictionarySendTypes", "Id");
            AddForeignKey("DMS.DictionarySendTypes", "SubordinationTypeId", "DMS.DictionarySubordinationTypes", "Id");
            AddForeignKey("DMS.AdminSubordinations", "SubordinationTypeId", "DMS.DictionarySubordinationTypes", "Id");
            AddForeignKey("DMS.DocumentSendLists", "StageTypeId", "DMS.DictionaryStageTypes", "Id");
            AddForeignKey("DMS.TemplateDocumentSendLists", "StageTypeId", "DMS.DictionaryStageTypes", "Id");
            AddForeignKey("DMS.DocumentEvents", "EventTypeId", "DMS.DictionaryEventTypes", "Id");
            AddForeignKey("DMS.DictionaryEventTypes", "ImportanceEventTypeId", "DMS.DictionaryImportanceEventTypes", "Id");
            AddForeignKey("DMS.DocumentFiles", "TypeId", "DMS.DictionaryFileTypes", "Id");
            AddForeignKey("DMS.TemplateDocumentFiles", "TypeId", "DMS.DictionaryFileTypes", "Id");
            AddForeignKey("DMS.DocumentWaits", "ResultTypeId", "DMS.DictionaryResultTypes", "Id");
            AddForeignKey("DMS.DocumentLinks", "LinkTypeId", "DMS.DictionaryLinkTypes", "Id");
            AddForeignKey("DMS.AdminRegistrationJournalPositions", "RegJournalAccessTypeId", "DMS.DicRegJournalAccessTypes", "Id");
            AddForeignKey("DMS.DocumentSubscriptions", "SigningTypeId", "DMS.DictionarySigningTypes", "Id");
            AddForeignKey("DMS.DocumentSubscriptions", "SubscriptionStateId", "DMS.DictionarySubscriptionStates", "Id");
            AddForeignKey("DMS.SystemSettings", "SettingTypeId", "DMS.DictionarySettingTypes", "Id");
            DropColumn("DMS.AdminAccessLevels", "LastChangeUserId");
            DropColumn("DMS.AdminAccessLevels", "LastChangeDate");
            DropColumn("DMS.DicPositionExecutorTypes", "LastChangeUserId");
            DropColumn("DMS.DicPositionExecutorTypes", "LastChangeDate");
            DropColumn("DMS.SystemActions", "API");
            DropColumn("DMS.SystemActions", "IsGrantable");
            DropColumn("DMS.SystemActions", "IsGrantableByRecordId");
            DropColumn("DMS.SystemActions", "IsVisible");
            DropColumn("DMS.SystemActions", "IsVisibleInMenu");
            DropColumn("DMS.AdminRoleTypes", "LastChangeUserId");
            DropColumn("DMS.AdminRoleTypes", "LastChangeDate");
            DropColumn("DMS.DictionaryDocumentDirections", "LastChangeUserId");
            DropColumn("DMS.DictionaryDocumentDirections", "LastChangeDate");
            DropColumn("DMS.DictionarySendTypes", "LastChangeUserId");
            DropColumn("DMS.DictionarySendTypes", "LastChangeDate");
            DropColumn("DMS.DictionarySubordinationTypes", "LastChangeUserId");
            DropColumn("DMS.DictionarySubordinationTypes", "LastChangeDate");
            DropColumn("DMS.DictionaryStageTypes", "LastChangeUserId");
            DropColumn("DMS.DictionaryStageTypes", "LastChangeDate");
            DropColumn("DMS.DictionaryEventTypes", "LastChangeUserId");
            DropColumn("DMS.DictionaryEventTypes", "LastChangeDate");
            DropColumn("DMS.DictionaryImportanceEventTypes", "LastChangeUserId");
            DropColumn("DMS.DictionaryImportanceEventTypes", "LastChangeDate");
            DropColumn("DMS.DictionaryFileTypes", "LastChangeUserId");
            DropColumn("DMS.DictionaryFileTypes", "LastChangeDate");
            DropColumn("DMS.DictionaryResultTypes", "IsActive");
            DropColumn("DMS.DictionaryResultTypes", "LastChangeUserId");
            DropColumn("DMS.DictionaryResultTypes", "LastChangeDate");
            DropColumn("DMS.DictionaryLinkTypes", "IsActive");
            DropColumn("DMS.DictionaryLinkTypes", "LastChangeUserId");
            DropColumn("DMS.DictionaryLinkTypes", "LastChangeDate");
            DropColumn("DMS.DicRegJournalAccessTypes", "LastChangeUserId");
            DropColumn("DMS.DicRegJournalAccessTypes", "LastChangeDate");
            DropColumn("DMS.DictionarySigningTypes", "LastChangeUserId");
            DropColumn("DMS.DictionarySigningTypes", "LastChangeDate");
            DropColumn("DMS.DictionarySubscriptionStates", "LastChangeUserId");
            DropColumn("DMS.DictionarySubscriptionStates", "LastChangeDate");
            DropColumn("DMS.DictionarySettingTypes", "LastChangeUserId");
            DropColumn("DMS.DictionarySettingTypes", "LastChangeDate");
            DropTable("DMS.SystemDates");
        }
        
        public override void Down()
        {
            CreateTable(
                "DMS.SystemDates",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Date = c.DateTime(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            AddColumn("DMS.DictionarySettingTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionarySettingTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionarySubscriptionStates", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionarySubscriptionStates", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionarySigningTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionarySigningTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DicRegJournalAccessTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DicRegJournalAccessTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionaryLinkTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionaryLinkTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionaryLinkTypes", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("DMS.DictionaryResultTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionaryResultTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionaryResultTypes", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("DMS.DictionaryFileTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionaryFileTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionaryImportanceEventTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionaryImportanceEventTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionaryEventTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionaryEventTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionaryStageTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionaryStageTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionarySubordinationTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionarySubordinationTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionarySendTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionarySendTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.DictionaryDocumentDirections", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DictionaryDocumentDirections", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.AdminRoleTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.AdminRoleTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.SystemActions", "IsVisibleInMenu", c => c.Boolean(nullable: false));
            AddColumn("DMS.SystemActions", "IsVisible", c => c.Boolean(nullable: false));
            AddColumn("DMS.SystemActions", "IsGrantableByRecordId", c => c.Boolean(nullable: false));
            AddColumn("DMS.SystemActions", "IsGrantable", c => c.Boolean(nullable: false));
            AddColumn("DMS.SystemActions", "API", c => c.String(maxLength: 2000));
            AddColumn("DMS.DicPositionExecutorTypes", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.DicPositionExecutorTypes", "LastChangeUserId", c => c.Int(nullable: false));
            AddColumn("DMS.AdminAccessLevels", "LastChangeDate", c => c.DateTime(nullable: false));
            AddColumn("DMS.AdminAccessLevels", "LastChangeUserId", c => c.Int(nullable: false));
            DropForeignKey("DMS.SystemSettings", "SettingTypeId", "DMS.DictionarySettingTypes");
            DropForeignKey("DMS.DocumentSubscriptions", "SubscriptionStateId", "DMS.DictionarySubscriptionStates");
            DropForeignKey("DMS.DocumentSubscriptions", "SigningTypeId", "DMS.DictionarySigningTypes");
            DropForeignKey("DMS.AdminRegistrationJournalPositions", "RegJournalAccessTypeId", "DMS.DicRegJournalAccessTypes");
            DropForeignKey("DMS.DocumentLinks", "LinkTypeId", "DMS.DictionaryLinkTypes");
            DropForeignKey("DMS.DocumentWaits", "ResultTypeId", "DMS.DictionaryResultTypes");
            DropForeignKey("DMS.TemplateDocumentFiles", "TypeId", "DMS.DictionaryFileTypes");
            DropForeignKey("DMS.DocumentFiles", "TypeId", "DMS.DictionaryFileTypes");
            DropForeignKey("DMS.DictionaryEventTypes", "ImportanceEventTypeId", "DMS.DictionaryImportanceEventTypes");
            DropForeignKey("DMS.DocumentEvents", "EventTypeId", "DMS.DictionaryEventTypes");
            DropForeignKey("DMS.TemplateDocumentSendLists", "StageTypeId", "DMS.DictionaryStageTypes");
            DropForeignKey("DMS.DocumentSendLists", "StageTypeId", "DMS.DictionaryStageTypes");
            DropForeignKey("DMS.AdminSubordinations", "SubordinationTypeId", "DMS.DictionarySubordinationTypes");
            DropForeignKey("DMS.DictionarySendTypes", "SubordinationTypeId", "DMS.DictionarySubordinationTypes");
            DropForeignKey("DMS.TemplateDocumentSendLists", "SendTypeId", "DMS.DictionarySendTypes");
            DropForeignKey("DMS.DocumentSendLists", "SendTypeId", "DMS.DictionarySendTypes");
            DropForeignKey("DMS.DicStandartSendListContents", "SendTypeId", "DMS.DictionarySendTypes");
            DropForeignKey("DMS.TemplateDocuments", "DocumentDirectionId", "DMS.DictionaryDocumentDirections");
            DropForeignKey("DMS.Documents", "DocumentDirectionId", "DMS.DictionaryDocumentDirections");
            DropForeignKey("DMS.SystemUIElements", "ValueTypeId", "DMS.SystemValueTypes");
            DropForeignKey("DMS.Properties", "ValueTypeId", "DMS.SystemValueTypes");
            DropForeignKey("DMS.SystemSettings", "ValueTypeId", "DMS.SystemValueTypes");
            DropForeignKey("DMS.SystemFields", "ValueTypeId", "DMS.SystemValueTypes");
            DropForeignKey("DMS.PropertyLinks", "ObjectId", "DMS.SystemObjects");
            DropForeignKey("DMS.SystemLogs", "ObjectId", "DMS.SystemObjects");
            DropForeignKey("DMS.SystemFields", "ObjectId", "DMS.SystemObjects");
            DropForeignKey("DMS.SystemActions", "ObjectId", "DMS.SystemObjects");
            DropForeignKey("DMS.SystemUIElements", "ActionId", "DMS.SystemActions");
            DropForeignKey("DMS.SystemLogs", "ActionId", "DMS.SystemActions");
            DropForeignKey("DMS.SystemActions", "SystemActions_Id", "DMS.SystemActions");
            DropForeignKey("DMS.DictionaryPositions", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentLinks", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.Documents", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentEvents", "TargetPositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentEvents", "SourcePositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentFiles", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentTasks", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentSendLists", "TargetPositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentSendLists", "SourcePositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentEventAccesses", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DocumentSubscriptions", "CertificatePositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.DictionaryPositionExecutors", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes");
            DropForeignKey("DMS.TemplateDocumentSendLists", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.TempDocRestrictedSendLists", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.DocumentRestrictedSendLists", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.DocumentSendLists", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.DicStandartSendListContents", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.DictionaryPositionExecutors", "AccessLevelId", "DMS.AdminAccessLevels");
            DropForeignKey("DMS.DocumentAccesses", "AccessLevelId", "DMS.AdminAccessLevels");
            DropPrimaryKey("DMS.SystemUIElements");
            DropPrimaryKey("DMS.SystemPatterns");
            DropPrimaryKey("DMS.SystemFormulas");
            DropPrimaryKey("DMS.SystemFormats");
            DropPrimaryKey("DMS.DictionarySettingTypes");
            DropPrimaryKey("DMS.DictionarySubscriptionStates");
            DropPrimaryKey("DMS.DictionarySigningTypes");
            DropPrimaryKey("DMS.DicRegJournalAccessTypes");
            DropPrimaryKey("DMS.DictionaryLinkTypes");
            DropPrimaryKey("DMS.DictionaryResultTypes");
            DropPrimaryKey("DMS.DictionaryFileTypes");
            DropPrimaryKey("DMS.DictionaryImportanceEventTypes");
            DropPrimaryKey("DMS.DictionaryEventTypes");
            DropPrimaryKey("DMS.DictionaryStageTypes");
            DropPrimaryKey("DMS.DictionarySubordinationTypes");
            DropPrimaryKey("DMS.DictionarySendTypes");
            DropPrimaryKey("DMS.DictionaryDocumentDirections");
            DropPrimaryKey("DMS.SystemValueTypes");
            DropPrimaryKey("DMS.SystemFields");
            DropPrimaryKey("DMS.SystemObjects");
            DropPrimaryKey("DMS.SystemActions");
            DropPrimaryKey("DMS.DicPositionExecutorTypes");
            DropPrimaryKey("DMS.AdminAccessLevels");
            AlterColumn("DMS.SystemUIElements", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.SystemPatterns", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.SystemFormulas", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.SystemFormats", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionarySettingTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionarySubscriptionStates", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionarySigningTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DicRegJournalAccessTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionaryLinkTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionaryResultTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionaryFileTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionaryImportanceEventTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionaryEventTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionaryStageTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionarySubordinationTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionarySendTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DictionaryDocumentDirections", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.SystemValueTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.SystemFields", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.SystemObjects", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.SystemActions", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.DicPositionExecutorTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("DMS.AdminAccessLevels", "Id", c => c.Int(nullable: false, identity: true));
            DropColumn("DMS.DictionarySigningTypes", "Code");
            DropColumn("DMS.DictionaryFileTypes", "Code");
            AddPrimaryKey("DMS.SystemUIElements", "Id");
            AddPrimaryKey("DMS.SystemPatterns", "Id");
            AddPrimaryKey("DMS.SystemFormulas", "Id");
            AddPrimaryKey("DMS.SystemFormats", "Id");
            AddPrimaryKey("DMS.DictionarySettingTypes", "Id");
            AddPrimaryKey("DMS.DictionarySubscriptionStates", "Id");
            AddPrimaryKey("DMS.DictionarySigningTypes", "Id");
            AddPrimaryKey("DMS.DicRegJournalAccessTypes", "Id");
            AddPrimaryKey("DMS.DictionaryLinkTypes", "Id");
            AddPrimaryKey("DMS.DictionaryResultTypes", "Id");
            AddPrimaryKey("DMS.DictionaryFileTypes", "Id");
            AddPrimaryKey("DMS.DictionaryImportanceEventTypes", "Id");
            AddPrimaryKey("DMS.DictionaryEventTypes", "Id");
            AddPrimaryKey("DMS.DictionaryStageTypes", "Id");
            AddPrimaryKey("DMS.DictionarySubordinationTypes", "Id");
            AddPrimaryKey("DMS.DictionarySendTypes", "Id");
            AddPrimaryKey("DMS.DictionaryDocumentDirections", "Id");
            AddPrimaryKey("DMS.SystemValueTypes", "Id");
            AddPrimaryKey("DMS.SystemFields", "Id");
            AddPrimaryKey("DMS.SystemObjects", "Id");
            AddPrimaryKey("DMS.SystemActions", "Id");
            AddPrimaryKey("DMS.DicPositionExecutorTypes", "Id");
            AddPrimaryKey("DMS.AdminAccessLevels", "Id");
            RenameIndex(table: "DMS.SystemActions", name: "IX_SystemActions_Id", newName: "IX_GrantId");
            RenameColumn(table: "DMS.SystemActions", name: "SystemActions_Id", newName: "GrantId");
            AddForeignKey("DMS.SystemSettings", "SettingTypeId", "DMS.DictionarySettingTypes", "Id");
            AddForeignKey("DMS.DocumentSubscriptions", "SubscriptionStateId", "DMS.DictionarySubscriptionStates", "Id");
            AddForeignKey("DMS.DocumentSubscriptions", "SigningTypeId", "DMS.DictionarySigningTypes", "Id");
            AddForeignKey("DMS.AdminRegistrationJournalPositions", "RegJournalAccessTypeId", "DMS.DicRegJournalAccessTypes", "Id");
            AddForeignKey("DMS.DocumentLinks", "LinkTypeId", "DMS.DictionaryLinkTypes", "Id");
            AddForeignKey("DMS.DocumentWaits", "ResultTypeId", "DMS.DictionaryResultTypes", "Id");
            AddForeignKey("DMS.TemplateDocumentFiles", "TypeId", "DMS.DictionaryFileTypes", "Id");
            AddForeignKey("DMS.DocumentFiles", "TypeId", "DMS.DictionaryFileTypes", "Id");
            AddForeignKey("DMS.DictionaryEventTypes", "ImportanceEventTypeId", "DMS.DictionaryImportanceEventTypes", "Id");
            AddForeignKey("DMS.DocumentEvents", "EventTypeId", "DMS.DictionaryEventTypes", "Id");
            AddForeignKey("DMS.TemplateDocumentSendLists", "StageTypeId", "DMS.DictionaryStageTypes", "Id");
            AddForeignKey("DMS.DocumentSendLists", "StageTypeId", "DMS.DictionaryStageTypes", "Id");
            AddForeignKey("DMS.AdminSubordinations", "SubordinationTypeId", "DMS.DictionarySubordinationTypes", "Id");
            AddForeignKey("DMS.DictionarySendTypes", "SubordinationTypeId", "DMS.DictionarySubordinationTypes", "Id");
            AddForeignKey("DMS.TemplateDocumentSendLists", "SendTypeId", "DMS.DictionarySendTypes", "Id");
            AddForeignKey("DMS.DocumentSendLists", "SendTypeId", "DMS.DictionarySendTypes", "Id");
            AddForeignKey("DMS.DicStandartSendListContents", "SendTypeId", "DMS.DictionarySendTypes", "Id");
            AddForeignKey("DMS.TemplateDocuments", "DocumentDirectionId", "DMS.DictionaryDocumentDirections", "Id");
            AddForeignKey("DMS.Documents", "DocumentDirectionId", "DMS.DictionaryDocumentDirections", "Id");
            AddForeignKey("DMS.SystemUIElements", "ValueTypeId", "DMS.SystemValueTypes", "Id");
            AddForeignKey("DMS.Properties", "ValueTypeId", "DMS.SystemValueTypes", "Id");
            AddForeignKey("DMS.SystemSettings", "ValueTypeId", "DMS.SystemValueTypes", "Id");
            AddForeignKey("DMS.SystemFields", "ValueTypeId", "DMS.SystemValueTypes", "Id");
            AddForeignKey("DMS.PropertyLinks", "ObjectId", "DMS.SystemObjects", "Id");
            AddForeignKey("DMS.SystemLogs", "ObjectId", "DMS.SystemObjects", "Id");
            AddForeignKey("DMS.SystemFields", "ObjectId", "DMS.SystemObjects", "Id");
            AddForeignKey("DMS.SystemActions", "ObjectId", "DMS.SystemObjects", "Id");
            AddForeignKey("DMS.SystemUIElements", "ActionId", "DMS.SystemActions", "Id");
            AddForeignKey("DMS.SystemLogs", "ActionId", "DMS.SystemActions", "Id");
            AddForeignKey("DMS.SystemActions", "GrantId", "DMS.SystemActions", "Id");
            AddForeignKey("DMS.DictionaryPositions", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentLinks", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.Documents", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentEvents", "TargetPositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentEvents", "SourcePositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentFiles", "ExecutorPositionExeTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentTasks", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentSendLists", "TargetPositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentSendLists", "SourcePositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentEventAccesses", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DocumentSubscriptions", "CertificatePositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.DictionaryPositionExecutors", "PositionExecutorTypeId", "DMS.DicPositionExecutorTypes", "Id");
            AddForeignKey("DMS.TemplateDocumentSendLists", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.TempDocRestrictedSendLists", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.DocumentRestrictedSendLists", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.DocumentSendLists", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.DicStandartSendListContents", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.DictionaryPositionExecutors", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
            AddForeignKey("DMS.DocumentAccesses", "AccessLevelId", "DMS.AdminAccessLevels", "Id");
        }
    }
}
