// <auto-generated />
namespace DMS_WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LockoutAgentUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LockoutAgentUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201611082050340_LockoutAgentUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
