//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminSettings
    {
        public int Id { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int SettingTypeId { get; set; }
        public string ValueString { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<double> ValueNumeric { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual DictionaryPositions Position { get; set; }
        public virtual DictionaryAgentUsers User { get; set; }
        public virtual AdninSettingTypes SettingType { get; set; }
    }
}
