//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdninSettingTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdninSettingTypes()
        {
            this.Settings = new HashSet<AdminSettings>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int ValueTypeId { get; set; }
        public bool IsGeneral { get; set; }
        public bool IsPosition { get; set; }
        public bool IsUser { get; set; }
        public bool IsAdminOnly { get; set; }
        public string DefaultValueString { get; set; }
        public Nullable<System.DateTime> DefaultValueDate { get; set; }
        public Nullable<double> DefaultValueNumeric { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminSettings> Settings { get; set; }
        public virtual SystemValueTypes ValueType { get; set; }
    }
}
