//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionaryAgentPersons
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string TaxCode { get; set; }
        public bool IsMale { get; set; }
        public string PassportSerial { get; set; }
        public Nullable<int> PassportNumber { get; set; }
        public string PassportText { get; set; }
        public Nullable<System.DateTime> PassportDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> AgentCompanyId { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual DictionaryAgents Agent { get; set; }
        public virtual DictionaryAgentCompanies AgentCompany { get; set; }
    }
}
