//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionaryStandartSendListContents
    {
        public int Id { get; set; }
        public int StandartSendListId { get; set; }
        public int Stage { get; set; }
        public int SendTypeId { get; set; }
        public Nullable<int> TargetPositionId { get; set; }
        public Nullable<int> TargetAgentId { get; set; }
        public string Description { get; set; }
        public string Task { get; set; }
        public Nullable<int> DueDay { get; set; }
        public Nullable<int> AccessLevelId { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual DictionaryStandartSendLists StandartSendList { get; set; }
        public virtual DictionarySendTypes SendType { get; set; }
        public virtual DictionaryPositions TargetPosition { get; set; }
        public virtual DictionaryAgents TargetAgents { get; set; }
        public virtual AdminAccessLevels AccessLevel { get; set; }
    }
}
