//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionaryAgentAccounts
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public string Name { get; set; }
        public int AgentBankId { get; set; }
        public string AccountNumber { get; set; }
        public bool IsMain { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual DictionaryAgents Agent { get; set; }
        public virtual DictionaryAgentBanks AgentBank { get; set; }
    }
}
