//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionaryPositionExecutors
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public int PositionId { get; set; }
        public int PositionExecutorTypeId { get; set; }
        public int AccessLevelId { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual DictionaryPositions Position { get; set; }
        public virtual DictionaryAgents Agent { get; set; }
        public virtual DictionaryPositionExecutorTypes PositionExecutorType { get; set; }
        public virtual AdminAccessLevels AccessLevel { get; set; }
    }
}
