//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentFiles
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public string Name { get; set; }
        public int OrderNumber { get; set; }
        public int Version { get; set; }
        public string Extention { get; set; }
        public string FileType { get; set; }
        public System.DateTime Date { get; set; }
        public byte[] Content { get; set; }
        public bool IsAdditional { get; set; }
        public string Hash { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual Documents Document { get; set; }
    }
}
