//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSubscriptions
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public int SendEventId { get; set; }
        public Nullable<int> DoneEventId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> SubscriptionStateId { get; set; }
        public string Hash { get; set; }
        public string ChangedHash { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual Documents Document { get; set; }
        public virtual DocumentEvents SendEvent { get; set; }
        public virtual DocumentEvents DoneEvent { get; set; }
        public virtual DictionarySubscriptionStates SubscriptionState { get; set; }
    }
}
