//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentWaits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentWaits()
        {
            this.ChildWaits = new HashSet<DocumentWaits>();
        }
    
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int OnEventId { get; set; }
        public Nullable<int> OffEventId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> AttentionDate { get; set; }
        public Nullable<int> ResultTypeId { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual Documents Document { get; set; }
        public virtual DocumentWaits ParentWait { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentWaits> ChildWaits { get; set; }
        public virtual DocumentEvents OnEvent { get; set; }
        public virtual DocumentEvents OffEvent { get; set; }
        public virtual DictionaryResultTypes ResultType { get; set; }
    }
}
