//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentEvents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentEvents()
        {
            this.OnWait = new HashSet<DocumentWaits>();
            this.OffWait = new HashSet<DocumentWaits>();
            this.SendSubscription = new HashSet<DocumentSubscriptions>();
            this.DoneSubscription = new HashSet<DocumentSubscriptions>();
            this.StartSendList = new HashSet<DocumentSendLists>();
            this.CloseSendList = new HashSet<DocumentSendLists>();
            this.EventReaders = new HashSet<DocumentEventReaders>();
            this.PaperEvents = new HashSet<DocumentPaperEvents>();
        }
    
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public int EventTypeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string Description { get; set; }
        public Nullable<int> SourcePositionId { get; set; }
        public Nullable<int> SourcePositionExecutorAgentId { get; set; }
        public int SourceAgentId { get; set; }
        public Nullable<int> TargetPositionId { get; set; }
        public Nullable<int> TargetPositionExecutorAgentId { get; set; }
        public Nullable<int> TargetAgentId { get; set; }
        public bool IsAvailableWithinTask { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<int> ReadAgentId { get; set; }
        public Nullable<int> PaperId { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual Documents Document { get; set; }
        public virtual DictionaryEventTypes EventType { get; set; }
        public virtual DictionaryPositions SourcePosition { get; set; }
        public virtual DictionaryAgents SourceAgent { get; set; }
        public virtual DictionaryPositions TargetPosition { get; set; }
        public virtual DictionaryAgents TargetAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentWaits> OnWait { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentWaits> OffWait { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSubscriptions> SendSubscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSubscriptions> DoneSubscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSendLists> StartSendList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSendLists> CloseSendList { get; set; }
        public virtual DictionaryAgents ReadAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentEventReaders> EventReaders { get; set; }
        public virtual DocumentTasks TaskD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentPaperEvents> PaperEvents { get; set; }
    }
}
