//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentEventReaders
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<int> ReadAgentId { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual DocumentEvents Event { get; set; }
        public virtual DictionaryPositions Position { get; set; }
        public virtual DictionaryAgents Agent { get; set; }
        public virtual DictionaryAgents ReadAgent { get; set; }
    }
}
