//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyLinks
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public int ObjectId { get; set; }
        public string Filers { get; set; }
        public bool IsMandatory { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual Properties Property { get; set; }
        public virtual SystemObjects Object { get; set; }
    }
}
