//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyValues
    {
        public int Id { get; set; }
        public int PropertyLinkId { get; set; }
        public int RecordId { get; set; }
        public string ValueString { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<double> ValueNumeric { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual PropertyLinks PropertyLink { get; set; }
    }
}
