//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string TypeCode { get; set; }
        public string Description { get; set; }
        public string Label { get; set; }
        public string Hint { get; set; }
        public Nullable<int> ValueTypeId { get; set; }
        public string OutFormat { get; set; }
        public string InputFormat { get; set; }
        public string SelectAPI { get; set; }
        public string SelectFilter { get; set; }
        public string SelectFieldCode { get; set; }
        public string SelectDescriptionFieldCode { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        public virtual SystemValueTypes ValueType { get; set; }
    }
}
