//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemFields
    {
        public int Id { get; set; }
        public int ObjectId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int ValueTypeId { get; set; }
    
        public virtual SystemObjects Object { get; set; }
        public virtual SystemValueTypes ValueTypes { get; set; }
    }
}
