//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDocuments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateDocuments()
        {
            this.SendLists = new HashSet<TemplateDocumentSendLists>();
            this.RestrictedSendLists = new HashSet<TemplateDocumentRestrictedSendLists>();
            this.DocumentFiles = new HashSet<TemplateDocumentFiles>();
            this.Tasks = new HashSet<TemplateDocumentTasks>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsHard { get; set; }
        public int DocumentDirectionId { get; set; }
        public int DocumentTypeId { get; set; }
        public Nullable<int> DocumentSubjectId { get; set; }
        public string Description { get; set; }
        public Nullable<int> RegistrationJournalId { get; set; }
        public Nullable<int> SenderAgentId { get; set; }
        public Nullable<int> SenderAgentPersonId { get; set; }
        public string Addressee { get; set; }
        public int LastChangeUserId { get; set; }
        public System.DateTime LastChangeDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateDocumentSendLists> SendLists { get; set; }
        public virtual DictionaryDocumentDirections DocumentDirection { get; set; }
        public virtual DictionaryDocumentTypes DocumentType { get; set; }
        public virtual DictionaryDocumentSubjects DocumentSubject { get; set; }
        public virtual DictionaryRegistrationJournals RegistrationJournal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateDocumentRestrictedSendLists> RestrictedSendLists { get; set; }
        public virtual DictionaryAgents SenderAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateDocumentFiles> DocumentFiles { get; set; }
        public virtual DictionaryAgentPersons SenderAgentPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateDocumentTasks> Tasks { get; set; }
    }
}
